### ISSUE TITLE
Synology NAS docker how to?

### ISSUE THREAD

**Issue by spider7611** [MaartenSanders/ycast-docker#2]
Hi,

I donwload this docker with this:
**sudo docker run -d --name vtuner-ycast -v /volume1/docker/vtuner/:/srv/ycast/ycast/stations/ -p 8383:80 --restart unless-stopped netraams/ycast-docker**
Started and say this: "ERROR: Station configuration '/opt/ycast/stations.yml' not found"
In the browser http://192.168.1.120:8383/ycast/ get this: **1Dirhttp://192.168.1.120:8383/ycast/radiobrowser/?vtuner=truehttp://192.168.1.120:8383/ycast/radiobrowser/?vtuner=true4Display'My Stations' feature not configured.**
I'm not an expert so can you help how to add this stations.yml?
On /volume1/docker/vtuner make this directory. 
And how can this working with my Denon and synology nas? Or can you give a step by step instruction?
On my synology have adguard docker too, is it good for DNS resolve?

**Comment by MaartenSanders** [comment]
I think you are not mapping to the right path inside your container. For me it works with:
**.... -v /mnt/data/docker_appdata/ycast/opt/ycast/:/opt/ycast/stations ** where /opt/ycast/stations is the path inside the container sot his should for you be the same. For /mnt/data/docker_appdata/ycast/opt/ycast/ you can pick any folder on your host where you place stations.yml in your case: 
sudo docker run -d --name vtuner-ycast -v /volume1/docker/vtuner/:/opt/ycast/stations -p 8383:80 --restart unless-stopped netraams/ycast-docker
I can't comment on DNS as i don't have a Synology and Denon but once you have DNS setup and it is pointing the url your Denon expects to the docker container it should work.

**Comment by MaartenSanders** [comment]
please check https://digiism.com/2020/03/23/fix-online-radio-on-your-receiver-with-a-self-hosted-vtuner/
