### ISSUE TITLE
Problem with my stations

### ISSUE THREAD

**Issue by aehk** [MaartenSanders/ycast-docker#3]
Sorry but after looping for a while and pressing google - I am desperate and have to bother you.
I set up a portainer docker compose for my synology:
________________________________________________________________________________
version: '2'
services:
  ycast:
    image: netraams/ycast-docker:latest
    container_name: ycast
    restart: always
    networks:
      mynet:
        ipv4_address: 192.168.178.194
    volumes: 
      - /volume3/docker/ycast_data/:/opt/ycast/stations
networks:
  mynet:
    external: true
__________________________________________________________________________________

I set the ENV YC_Stations to "/opt/ycast/stations/stations.yml"
so all should be fine .... even looked into the container and I can see the example stations.yml
but still I get in the browser:
"1Dirhttp://192.168.178.194/ycast/radiobrowser/?vtuner=truehttp://192.168.178.194/ycast/radiobrowser/?vtuner=true4Display'My Stations' feature not configured."
and Log shows:
"2022-05-04 13:54:54 INFO: YCast (1.1.0) server starting
2022-05-04 13:54:54 ERROR: Station configuration '/opt/ycast/stations.yml' not found"

Thank you for your support!

**Comment by MaartenSanders** [comment]
Assuming you have `stations.yml` in `/volume3/docker/ycast_data/` change the line with the volumes in your docker-compose.yml to:

`- /volumes3/docker/ycast_data/:/opt/ycast`

Note, I don’t have a Synology.

**Comment by aehk** [comment]
Thank you for fast respone :-)
Then the service does not start ... and I get "/usr/bin/python3: No module named ycast".
Where can I look to get this ironed out?

**Comment by MaartenSanders** [comment]
Can you paste the full log output and enable debug with the environment variable ?

Note I have a bind volume in my my setup:
Set YC_STATIONS=/opt/ycast/stations/stations.yml and bind a volume to /opt/ycast/stations/ where I drop my stations.yml file.

See the example in my docker-compose.yml I just added to 'master'.

**Comment by aehk** [comment]
I tried the docker compose - and had to adjust is to my settings - seems it starts now as I see in browser_
"-1Dirhttp://192.168.178.193/ycast/radiobrowser/?vtuner=truehttp://192.168.178.193/ycast/radiobrowser/?vtuner=true4Dirhttp://192.168.178.193/ycast/my_stations/?vtuner=truehttp://192.168.178.193/ycast/my_stations/?vtuner=true4"
But nothing else happens ... I expected a browser for the stations.
The log shows:
_________________________________________________________________________________________________________________
2022-05-05 08:07:38 INFO: YCast (1.1.0) server starting
2022-05-05 08:07:38 DEBUG: Debug logging enabled
 * Serving Flask app 'ycast.server' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
2022-05-05 08:07:39 WARNING:  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
2022-05-05 08:07:39 INFO:  * Running on http://192.168.178.193:80/ (Press CTRL+C to quit)
2022-05-05 08:07:42 INFO: 192.168.178.60 - - [05/May/2022 08:07:42] "GET /ycast/ HTTP/1.1" 200 -
2022-05-05 08:07:42 INFO: 192.168.178.60 - - [05/May/2022 08:07:42] "GET /favicon.ico HTTP/1.1" 404 -
_________________________________________________________________________________________________________________

Strange that debug stays OFF despite setting ENV to ON
[docker-compose.txt](https://github.com/MaartenSanders/ycast-docker/files/8639479/docker-compose.txt)
In the docker I can see the stations.yml file - so mapping works..
Thx for you support and Sorry to be a bother.

**Comment by MaartenSanders** [comment]
You will not get a browser for radiostations. Please read [here](https://github.com/milaq/YCast)
Your tuner must connect to your ycast docker host believing it is the vtuner address it is looking for. I have a yamaha tuner so mine is at:
radioyamaha.vtuner.com where I point the DNS server of my router for this address to the docker host where ycast is running.
If you get a response like this:
`-1Dirhttp://radioyamaha.vtuner.com/ycast/radiobrowser/?vtuner=truehttp://radioyamaha.vtuner.com/ycast/radiobrowser/?vtuner=true4Dirhttp://radioyamaha.vtuner.com/ycast/my_stations/?vtuner=truehttp://radioyamaha.vtuner.com/ycast/my_stations/?vtuner=true4`
in and ordinary webbrowser when you point that to http://ip-or-address-of-your-ycast-docker-host/ycast then your setup is working.
I am closing this thread.

**Comment by aehk** [comment]
Thank you!!! Your compose file and "radioyamaha" did the trick!!
